version: "3"
services:      
 couchdb:
  image: "couchdb"  
  hostname: "couchdb"
  restart: unless-stopped
  #env_file:
  # - "build/couch.env"
  environment:
   - COUCHDB_USER=admin
   - COUCHDB_PASSWORD=abc123.
  ports:
   - "5984:5984"
  volumes:
        - ./dbdata:/opt/couchdb/data

