version: "3"
services:      
 nginx:
  image: "nginx:latest"
  hostname: "nginx"
  ports:
   - "8080:80"
   - "443:443"
  volumes:
   - ./nginx/html:/var/www/html
   - ./nginx/ssl:/etc/nginx/ssl
   - ./website/miniblog:/etc/nginx/sites-available/miniblog:ro
 couchdb:
  image: "couchdb"  
  hostname: "couchdb"
  environment:
   - COUCHDB_USER=admin
   - COUCHDB_PASSWORD=abc123.
  ports:
   - "5984:5984"
  volumes:
   - ./couchdata:/opt/couchdb/data
 flask-gunicorn:
  build: ./flask
  hostname: "flask"
  ports:
   - "8000:8000"
  volumes:
   - ./website:/usr/src/website:ro

