version: "3"
services:      
 nginx:
  image: "nginx:latest"
  hostname: "nginx"
  restart: "unless-stopped"
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ./nginx/ssl:/etc/nginx/ssl
   - ./nginx/miniblog:/etc/nginx/conf.d/default.conf:ro
# couchdb:
#  image: "couchdb"  
#  hostname: "couchdb"
#  restart: "unless-stopped"
#  environment:
#   - COUCHDB_USER=admin
#   - COUCHDB_PASSWORD=abc123.
#  ports:
#   - "5984:5984"
#  volumes:
#   - couch-data:/opt/couchdb/data
# flask-gunicorn:
#  build: ./flask
#  hostname: "flask"
#  restart: "unless-stopped"
#  volumes:
#   - ./website:/opt/web2print/website
#   - ./uploads:/opt/web2print/uploads
 #INSTANCIAS FLASK
 web2print:
  build: ./flask
  hostname: "web2print"
  restart: "unless-stopped"
  extra_hosts:
    - "copiasdeautor.jpereira.net:192.168.32.3" #host and ip
  depends_on:
  - mariadb
  volumes:
   - ./website_publico:/opt/web2print/website
   - ./uploads:/opt/web2print/uploads 
 controlw2p:
  build: ./flask
  hostname: "controlw2p"
  restart: "unless-stopped"
  extra_hosts:
    - "copiasdeautor.jpereira.net:192.168.32.3" #host and ip
  depends_on:
  - mariadb
  volumes:
   - ./website_control:/opt/web2print/website
   - ./uploads:/opt/web2print/uploads
   - ./processes:/opt/web2print/processes
   - ./queue:/opt/web2print/queue 
   - ./reports:/opt/web2print/reports
   - ./temp:/opt/web2print/temp
 #MARIADB
 mariadb:
  build: ./mariadb
  hostname: "mariadb"
  restart: "unless-stopped"
  environment:
  - DB=web2print
  - DBUSER=copias
  - DBPASS=12345
  - WPDB=wpdb
  - WPUSER=wpuser
  - WPPASS=12345
  volumes:
   - mariadb-data:/var/lib/mysql
 #WORDPRESS
# wordpress:  
#  build:
#    context: wordpress
#    args:
#     ENVPATH: wordpress.build
#  hostname: wordpress
#  restart: "unless-stopped"
#  depends_on:
#  - mariadb
#  volumes:
#  - wp-data:/var/www/html/wordpress/data
 copiasdeautor:  
  build:
    context: wordpress
    args:
     ENVPATH: wordpress.build
  hostname: copiasdeautor
  restart: "unless-stopped"
  depends_on:
  - mariadb
  volumes:
  - wp-data:/var/www/html/wordpress/data
  - ./wordpress/000-default.conf:/etc/apache2/000-default.conf
  - ./wordpress/default-ssl.conf:/etc/apache2/default-ssl.conf
volumes:
 mariadb-data:
 couch-data:
 wp-data:

