version: "3"
services:      
 nginx:
  image: "nginx:latest"
  hostname: "nginx"
  ports:
   - "8080:80"
   - "443:443"
  volumes:
   - ./nginx/html:/var/www/html
   - ./nginx/conf:/etc/nginx
 couchdb:
  image: "couchdb"  
  hostname: "couchdb"
  environment:
   - COUCHDB_USER=admin
   - COUCHDB_PASSWORD=abc123.
  ports:
   - "5984:5984"
  volumes:
   - ./dbdata:/opt/couchdb/data
 flask-gunicorn:
  build: ./flask
  hostname: "flask"
  ports:
   - "5000:5000"
  volumes:
   - ./flask:/usr/src/app/

