version: "3"
services:      
 nginx:
  image: "nginx:latest"
  hostname: "nginx"
  restart: "unless-stopped"
  ports:
   - "8080:80"
   - "443:443"
  volumes:
   - ./nginx/ssl:/etc/nginx/ssl
   - ./nginx/miniblog:/etc/nginx/conf.d/default.conf:ro
 couchdb:
  image: "couchdb"  
  hostname: "couchdb"
  restart: "unless-stopped"
  environment:
   - COUCHDB_USER=admin
   - COUCHDB_PASSWORD=abc123.
  ports:
   - "5984:5984"
  volumes:
   - couch-data:/opt/couchdb/data
 flask-gunicorn:
  build: ./flask
  hostname: "flask"
  restart: "unless-stopped"
  ports:
   - "8000:8000"
  volumes:
   - ./website:/opt/web2print/website
 mariadb:
  build: ./mariadb
  hostname: "mariadb"
  restart: "unless-stopped"
  environment:
  - DB=web2print
  - DBUSER=copias
  - DBPASS=12345
  volumes:
   - mariadb-data:/var/lib/mysql
volumes:
 mariadb-data:
 couch-data:

